### ISSUE TITLE
Example saved setting doesn't work (KeyError: 9) 

### ISSUE THREAD

**Issue by ooker777** [kometenstaub/csv-to-md#12]
```ps
PS D:\GitHub\Obsidian\csv-to-md> python csv_to_md-file.py
saved_settings.py is already present
Do you want to load saved settings? Enter "y" for yes and "n" for no: y
Which settings do you want to choose? Please enter the name of the dictionary in saved_settings.py: save2
These are your selected settings: {'addYAML': 'n', 'column': {0: ['h2'], 1: ['ul'], 2: ['ta'], 3: ['ta', 'y', ','], 4: ['oc'], 5: ['ml'], 6: ['ta'], 7: ['ut'], 8: ['ut']}, 'delimiter': ',', 'fileNameCol': [0, 1], 'fileNameColSeparator': ' -- ', 'fileNameLength': 50, 'inlineYAML': 'y'}
Found file: Khảo sát-Grid view.csv
Traceback (most recent call last):
  File "D:\GitHub\Obsidian\csv-to-md\csv_to_md-file.py", line 390, in <module>
    startScript.choices()
  File "D:\GitHub\Obsidian\csv-to-md\csv_to_md-file.py", line 43, in choices
    self.mdChoices()
  File "D:\GitHub\Obsidian\csv-to-md\csv_to_md-file.py", line 64, in mdChoices
    instanceFile.makeMdFiles()
  File "D:\GitHub\Obsidian\csv-to-md\csv_to_md-file.py", line 213, in makeMdFiles
    if len(self.settings["column"][el]) > 1:
KeyError: 9
```

**Comment by kometenstaub** [comment]
It's just an example to show what it could look like, it's not supposed to be used. The settings depend on the number of columns.

To recreate the example in the README, you'd need to take the configuration I've shown in the GIF.

**Comment by ooker777** [comment]
I mean, the setting you make doesn't seem different from what I would make. And in my understanding any kind of setting would still work, because it's independent with the data?

**Comment by kometenstaub** [comment]
>  The settings depend on the number of columns.

**Comment by ooker777** [comment]
My bad 😞
